Repository masters2023-project-03-second-hand/second-hand-max-be-b, pull requests merged in 2023-10, with the labels that each got.

#129 관심상품 카테고리 목록 조회시 아이디도 함께 반환
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/wishitem.adoc
  src/main/java/kr/codesquad/secondhand/application/wishitem/WishItemService.java
  src/main/java/kr/codesquad/secondhand/presentation/WishItemController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/wishitem/WishItemCategoryResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/wishitem/WishItemCategoryResponses.java
  src/main/java/kr/codesquad/secondhand/repository/category/CategoryRepository.java
  src/main/resources/static/index.html
  src/test/java/kr/codesquad/secondhand/application/wishitem/WishItemServiceTest.java
  src/test/java/kr/codesquad/secondhand/documentation/wishitem/WishItemDocumentationTest.java
Labels: feat

#131 상품 목록 조회시 판매자도 함께 응답
  src/docs/asciidoc/item.adoc
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemResponse.java
  src/main/java/kr/codesquad/secondhand/repository/item/querydsl/ItemPaginationRepository.java
  src/main/resources/static/index.html
  src/test/java/kr/codesquad/secondhand/documentation/item/ItemDocumentationTest.java
  src/test/java/kr/codesquad/secondhand/documentation/wishitem/WishItemDocumentationTest.java
  src/test/java/kr/codesquad/secondhand/fixture/FixtureFactory.java
Labels: feat

#127 조회수 증가 로직 개선
  build.gradle
  src/main/java/kr/codesquad/secondhand/application/item/ItemReadFacade.java
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/application/item/ViewCountService.java
  src/main/java/kr/codesquad/secondhand/application/redis/RedisService.java
  src/main/java/kr/codesquad/secondhand/application/redis/ViewCountRedisService.java
  src/main/java/kr/codesquad/secondhand/config/AsyncConfig.java
  src/main/java/kr/codesquad/secondhand/config/RedisConfig.java
  src/main/java/kr/codesquad/secondhand/config/SchedulingConfig.java
  src/main/java/kr/codesquad/secondhand/domain/item/Item.java
  src/main/java/kr/codesquad/secondhand/presentation/ItemController.java
  src/main/java/kr/codesquad/secondhand/repository/item/ItemRepository.java
  src/main/java/kr/codesquad/secondhand/util/RedisUtil.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemConcurrencyTest.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemServiceTest.java
  src/test/java/kr/codesquad/secondhand/documentation/DocumentationTestSupport.java
  src/test/java/kr/codesquad/secondhand/documentation/item/ItemDocumentationTest.java
Labels: feat

#135 채팅방 목록 조회 로직 수정
  src/main/java/kr/codesquad/secondhand/application/chat/ChatLogService.java
  src/main/java/kr/codesquad/secondhand/application/chat/ChatRoomService.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatRoom.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/ApiResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/CustomSlice.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/ChatRequest.java
  src/test/java/kr/codesquad/secondhand/documentation/presentation/ChatControllerTest.java
Labels: bug

#140 회원 주소 목록 응답 형태 수정 및 회원 관련 테스트코드 작성
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member.adoc
  src/main/java/kr/codesquad/secondhand/application/residence/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/presentation/MemberController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/member/AddressData.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/member/MemberResidencesResponse.java
  src/main/resources/static/index.html
  src/test/java/kr/codesquad/secondhand/application/auth/KakaoRequesterTest.java
  src/test/java/kr/codesquad/secondhand/application/auth/NaverRequesterTest.java
  src/test/java/kr/codesquad/secondhand/documentation/member/MemberDocumentationTest.java
  src/test/java/kr/codesquad/secondhand/documentation/wishitem/WishItemDocumentationTest.java
Labels: test

#141 상품별 채팅목록 조회
  src/main/java/kr/codesquad/secondhand/application/chat/ChatRoomService.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/repository/chat/querydsl/ChatPaginationRepository.java
  src/test/java/kr/codesquad/secondhand/application/chat/ChatRoomServiceTest.java
  src/test/java/kr/codesquad/secondhand/documentation/presentation/ChatControllerTest.java
Labels: feat

#144 상품 상세 페이지 조회 응답 수정
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemDetailResponse.java
  src/main/java/kr/codesquad/secondhand/repository/chat/ChatRoomRepository.java
Labels: feat

#146 채팅 메시지 조회 응답 수정
  src/docs/asciidoc/chat.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/kr/codesquad/secondhand/application/chat/ChatLogService.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/ChatLogResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/SimpleChatLog.java
  src/main/java/kr/codesquad/secondhand/repository/chat/ChatLogRepository.java
  src/main/resources/static/index.html
  src/test/java/kr/codesquad/secondhand/documentation/chat/ChatDocumentationTest.java
  src/test/java/kr/codesquad/secondhand/documentation/presentation/ChatControllerTest.java
Labels: bug, feat

#148 상품 상세 페이지 응답 형식 통일
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/ChatLogResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemDetailResponse.java
  src/main/java/kr/codesquad/secondhand/repository/chat/ChatLogRepository.java
  src/main/resources/static/index.html
  src/test/java/kr/codesquad/secondhand/documentation/chat/ChatDocumentationTest.java
  src/test/java/kr/codesquad/secondhand/documentation/item/ItemDocumentationTest.java
Labels: feat

#150 Feature/#149 review
  src/main/java/kr/codesquad/secondhand/application/auth/KakaoRequester.java
  src/main/java/kr/codesquad/secondhand/application/auth/NaverRequester.java
  src/main/java/kr/codesquad/secondhand/application/auth/OAuthRequester.java
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/application/member/MemberService.java
  src/main/java/kr/codesquad/secondhand/application/redis/ViewCountRedisService.java
  src/main/java/kr/codesquad/secondhand/application/residence/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatLog.java
  src/main/java/kr/codesquad/secondhand/presentation/CategoryController.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/interceptor/RegionNotLoginInterceptor.java
Labels: refactor
