Repository masters2023-project-03-second-hand/second-hand-max-be-b, pull requests merged in 2023-09, with the labels that each got.

#39 상품 내용, 상태 수정
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/domain/item/Item.java
  src/main/java/kr/codesquad/secondhand/exception/ErrorCode.java
  src/main/java/kr/codesquad/secondhand/exception/ForbiddenException.java
  src/main/java/kr/codesquad/secondhand/exception/GlobalExceptionHandler.java
  src/main/java/kr/codesquad/secondhand/presentation/ItemController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemDetailResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemStatusRequest.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemUpdateRequest.java
  src/main/java/kr/codesquad/secondhand/repository/itemimage/ItemImageRepository.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemServiceTest.java
  src/test/java/kr/codesquad/secondhand/fixture/FixtureFactory.java
Labels: feat

#41 지역별 상품 조회
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/domain/item/Item.java
  src/main/java/kr/codesquad/secondhand/presentation/ItemController.java
  src/main/java/kr/codesquad/secondhand/repository/item/querydsl/ItemPaginationRepository.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/test/java/kr/codesquad/secondhand/acceptance/ItemAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemServiceTest.java
Labels: feat

#43 [Fix] db 정보를 가져오도록 수정
  src/main/resources/application.yml
Labels: bug

#47 2주차 리뷰사항 반영
  src/main/java/kr/codesquad/secondhand/application/auth/AuthService.java
  src/main/java/kr/codesquad/secondhand/application/auth/NaverRequester.java
  src/main/java/kr/codesquad/secondhand/application/auth/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/domain/AuditingFields.java
  src/main/java/kr/codesquad/secondhand/domain/item/Item.java
  src/main/java/kr/codesquad/secondhand/domain/itemimage/ItemImage.java
  src/main/java/kr/codesquad/secondhand/domain/member/Member.java
  src/main/java/kr/codesquad/secondhand/domain/member/UserProfile.java
  src/main/java/kr/codesquad/secondhand/domain/residence/Residence.java
  src/main/java/kr/codesquad/secondhand/presentation/AuthController.java
  src/main/java/kr/codesquad/secondhand/presentation/CategoryController.java
  src/main/java/kr/codesquad/secondhand/presentation/ItemController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemDetailResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemRegisterRequest.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemUpdateRequest.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/member/SignUpRequest.java
  src/main/resources/schema.sql
  src/test/java/kr/codesquad/secondhand/acceptance/AuthAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemServiceTest.java
  src/test/java/kr/codesquad/secondhand/fixture/FixtureFactory.java
Labels: feat

#52 관심상품 등록/해제
  src/main/java/kr/codesquad/secondhand/application/wishitem/WishItemService.java
  src/main/java/kr/codesquad/secondhand/domain/WishItem.java
  src/main/java/kr/codesquad/secondhand/domain/item/Item.java
  src/main/java/kr/codesquad/secondhand/presentation/WishItemController.java
  src/main/java/kr/codesquad/secondhand/repository/wishitem/WishItemRepository.java
  src/test/java/kr/codesquad/secondhand/acceptance/AcceptanceTestSupport.java
  src/test/java/kr/codesquad/secondhand/acceptance/ItemAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/acceptance/WishItemAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/wishitem/WishItemServiceTest.java
Labels: feat

#54 로그아웃 기능 구현
  build.gradle
  src/main/java/kr/codesquad/secondhand/application/auth/AuthService.java
  src/main/java/kr/codesquad/secondhand/config/OauthConfig.java
  src/main/java/kr/codesquad/secondhand/config/RedisConfig.java
  src/main/java/kr/codesquad/secondhand/infrastructure/OauthProvider.java
  src/main/java/kr/codesquad/secondhand/infrastructure/jwt/JwtExtractor.java
  src/main/java/kr/codesquad/secondhand/infrastructure/jwt/JwtProvider.java
  src/main/java/kr/codesquad/secondhand/infrastructure/properties/OauthProperties.java
  src/main/java/kr/codesquad/secondhand/infrastructure/properties/RedisProperties.java
  src/main/java/kr/codesquad/secondhand/presentation/AuthController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/filter/JwtFilter.java
  src/main/resources/application-redis.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/docker.yml
  src/test/java/kr/codesquad/secondhand/RedisTemplateCreator.java
  src/test/java/kr/codesquad/secondhand/TokenCreator.java
  src/test/java/kr/codesquad/secondhand/infrastructure/RedisTemplateTest.java
  src/test/java/kr/codesquad/secondhand/infrastructure/jwt/JwtProviderTest.java
Labels: feat

#59 관심상품 목록 조회
  src/main/java/kr/codesquad/secondhand/application/wishitem/WishItemService.java
  src/main/java/kr/codesquad/secondhand/domain/wishitem/WishItem.java
  src/main/java/kr/codesquad/secondhand/presentation/WishItemController.java
  src/main/java/kr/codesquad/secondhand/repository/wishitem/querydsl/WishItemPaginationRepository.java
  src/main/resources/schema.sql
  src/test/java/kr/codesquad/secondhand/acceptance/WishItemAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/wishitem/WishItemServiceTest.java
Labels: feat

#60 Docker hub를 이용하지 않는 CI/CD 환경으로의 변경
  .github/workflows/workflow.yml
  docker-compose-deploy.yml
Labels: infrastructure

#63 카테고리 조회 수정
  src/main/java/kr/codesquad/secondhand/presentation/dto/category/CategoryResponse.java
Labels: feat

#61 상품 삭제
  src/main/java/kr/codesquad/secondhand/application/image/ImageService.java
  src/main/java/kr/codesquad/secondhand/application/image/S3Uploader.java
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/config/AsyncConfig.java
  src/main/java/kr/codesquad/secondhand/exception/ErrorCode.java
  src/main/java/kr/codesquad/secondhand/presentation/ItemController.java
  src/main/java/kr/codesquad/secondhand/repository/itemimage/ItemImageRepository.java
  src/main/java/kr/codesquad/secondhand/repository/wishitem/WishItemRepository.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemServiceTest.java
Labels: feat

#67 관심상품 등록/해제시 관심 수 변경
  src/main/java/kr/codesquad/secondhand/application/wishitem/WishItemService.java
  src/main/java/kr/codesquad/secondhand/domain/item/Item.java
  src/test/java/kr/codesquad/secondhand/application/wishitem/WishItemServiceTest.java
Labels: feat

#69 카테고리 선택 시 redirect
  src/main/java/kr/codesquad/secondhand/presentation/RedirectController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/category/CategoryRequest.java
Labels: feat

#71 컨트롤러레이어가 아닌 서비스 레이어에서 예외처리하도록 수정
  src/main/java/kr/codesquad/secondhand/application/auth/AuthService.java
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/config/WebConfig.java
  src/main/java/kr/codesquad/secondhand/presentation/AuthController.java
  src/main/java/kr/codesquad/secondhand/presentation/ItemController.java
  src/main/java/kr/codesquad/secondhand/presentation/support/NotNullParam.java
  src/main/java/kr/codesquad/secondhand/presentation/support/NotNullParamArgumentResolver.java
  src/main/resources/application-local.yml
  src/test/java/kr/codesquad/secondhand/TestContainer.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemServiceTest.java
Labels: feat

#72 판매내역 조회
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/application/item/PagingUtils.java
  src/main/java/kr/codesquad/secondhand/application/item/SalesHistoryService.java
  src/main/java/kr/codesquad/secondhand/presentation/SalesHistoryController.java
  src/main/java/kr/codesquad/secondhand/repository/item/querydsl/ItemPaginationRepository.java
Labels: feat

#73 지역목록 조회
  src/main/java/kr/codesquad/secondhand/application/auth/AuthService.java
  src/main/java/kr/codesquad/secondhand/application/auth/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/application/item/PagingUtils.java
  src/main/java/kr/codesquad/secondhand/application/residence/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/application/wishitem/WishItemService.java
  src/main/java/kr/codesquad/secondhand/domain/residence/Region.java
  src/main/java/kr/codesquad/secondhand/domain/residence/Residence.java
  src/main/java/kr/codesquad/secondhand/presentation/ResidenceController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/member/SignUpRequest.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/residence/RegionResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/filter/JwtFilter.java
  src/main/java/kr/codesquad/secondhand/repository/PaginationRepository.java
  src/main/java/kr/codesquad/secondhand/repository/item/querydsl/ItemPaginationRepository.java
  src/main/java/kr/codesquad/secondhand/repository/residence/RegionRepository.java
  src/main/java/kr/codesquad/secondhand/repository/residence/querydsl/RegionPaginationRepository.java
  src/main/java/kr/codesquad/secondhand/repository/wishitem/querydsl/WishItemPaginationRepository.java
  src/main/resources/schema.sql
  src/test/java/kr/codesquad/secondhand/acceptance/ResidenceAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/residence/ResidenceServiceTest.java
Labels: feat

#79 3주차 리뷰 반영
  src/main/java/kr/codesquad/secondhand/application/auth/AuthService.java
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/application/residence/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/application/wishitem/WishItemService.java
  src/main/java/kr/codesquad/secondhand/config/ObjectMapperConfig.java
  src/main/java/kr/codesquad/secondhand/domain/AuditingFields.java
  src/main/java/kr/codesquad/secondhand/domain/wishitem/WishItem.java
  src/main/java/kr/codesquad/secondhand/exception/NotFoundException.java
  src/main/java/kr/codesquad/secondhand/presentation/AuthController.java
  src/main/java/kr/codesquad/secondhand/presentation/CategoryController.java
  src/main/java/kr/codesquad/secondhand/presentation/ItemController.java
  src/main/java/kr/codesquad/secondhand/presentation/RedirectController.java
  src/main/java/kr/codesquad/secondhand/presentation/ResidenceController.java
  src/main/java/kr/codesquad/secondhand/presentation/SalesHistoryController.java
  src/main/java/kr/codesquad/secondhand/presentation/WishItemController.java
  src/main/java/kr/codesquad/secondhand/repository/RedisRepository.java
  src/main/resources/application.yml
Labels: feat

#81 관심상품 목록 카테고리 조회
  src/main/java/kr/codesquad/secondhand/application/wishitem/WishItemService.java
  src/main/java/kr/codesquad/secondhand/presentation/WishItemController.java
  src/main/java/kr/codesquad/secondhand/repository/wishitem/querydsl/WishItemCategoryRepository.java
  src/test/java/kr/codesquad/secondhand/application/wishitem/WishItemServiceTest.java
Labels: feat

#80 거주지역 등록/삭제
  src/main/java/kr/codesquad/secondhand/application/auth/AuthService.java
  src/main/java/kr/codesquad/secondhand/application/residence/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/domain/residence/Residence.java
  src/main/java/kr/codesquad/secondhand/exception/NotFoundException.java
  src/main/java/kr/codesquad/secondhand/presentation/ResidenceController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/residence/ResidenceRequest.java
  src/main/java/kr/codesquad/secondhand/presentation/filter/JwtFilter.java
  src/main/java/kr/codesquad/secondhand/repository/residence/RegionRepository.java
  src/main/java/kr/codesquad/secondhand/repository/residence/ResidenceRepository.java
  src/test/java/kr/codesquad/secondhand/acceptance/ResidenceAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/residence/ResidenceServiceTest.java
Labels: feat

#83 s3이미지 삭제 기능 수정
  src/main/java/kr/codesquad/secondhand/application/image/ImageService.java
  src/main/java/kr/codesquad/secondhand/application/image/S3Uploader.java
Labels: bug, refactor

#85 프로필 이미지 수정
  src/main/java/kr/codesquad/secondhand/application/member/MemberService.java
  src/main/java/kr/codesquad/secondhand/domain/member/Member.java
  src/main/java/kr/codesquad/secondhand/presentation/MemberController.java
  src/test/java/kr/codesquad/secondhand/acceptance/MemberAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/member/MemberServiceTest.java
Labels: feat

#87 관심상품 등록/해제 리팩터링
  src/main/java/kr/codesquad/secondhand/config/WebConfig.java
  src/main/java/kr/codesquad/secondhand/presentation/WishItemController.java
  src/main/java/kr/codesquad/secondhand/presentation/support/converter/IsWish.java
  src/main/java/kr/codesquad/secondhand/presentation/support/converter/IsWishRequestConverter.java
Labels: refactor

#88 로그인하지 않은 사용자 메인화면 조회
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/presentation/ItemController.java
  src/main/java/kr/codesquad/secondhand/presentation/filter/JwtFilter.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemServiceTest.java
  src/test/java/kr/codesquad/secondhand/fixture/FixtureFactory.java
  src/test/java/kr/codesquad/secondhand/infrastructure/jwt/JwtProviderTest.java
Labels: feat

#90 채팅 관련 스키마 및 엔티티 작성
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatLog.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatRoom.java
  src/main/java/kr/codesquad/secondhand/domain/chat/WhoIsLast.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
Labels: docs, feat

#94 거주지역 등록 / 삭제 요청 및 로그인 성공 응답 API 수정
  src/main/java/kr/codesquad/secondhand/application/auth/AuthService.java
  src/main/java/kr/codesquad/secondhand/application/residence/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/exception/NotFoundException.java
  src/main/java/kr/codesquad/secondhand/presentation/ResidenceController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/member/AddressData.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/member/UserResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/residence/ResidenceRequest.java
  src/main/java/kr/codesquad/secondhand/repository/residence/ResidenceRepository.java
  src/main/java/kr/codesquad/secondhand/repository/residence/querydsl/ResidenceRepositoryCustom.java
  src/main/java/kr/codesquad/secondhand/repository/residence/querydsl/ResidenceRepositoryImpl.java
  src/test/java/kr/codesquad/secondhand/acceptance/AuthAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/acceptance/ResidenceAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/residence/ResidenceServiceTest.java
Labels: feat, refactor

#97 채팅방 내 채팅 내역 조회
  src/main/java/kr/codesquad/secondhand/application/chat/ChatLogService.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatLog.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatRoom.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/ApiResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/ChatLogResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/SimpleChatLog.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemSimpleResponse.java
  src/main/java/kr/codesquad/secondhand/repository/chat/ChatLogRepository.java
  src/main/java/kr/codesquad/secondhand/repository/chat/ChatRoomRepository.java
Labels: feat

#99 CI시 테스트 리포트 확인 기능 추가
  .github/workflows/workflow.yml
Labels: feat

#101 Jacoco를 통한 코드 커버리지 측정
  .github/workflows/workflow.yml
  build.gradle
Labels: feat

#102 채팅 목록 조회 기능
  src/main/java/kr/codesquad/secondhand/application/chat/ChatRoomService.java
  src/main/java/kr/codesquad/secondhand/application/item/PagingUtils.java
  src/main/java/kr/codesquad/secondhand/application/wishitem/WishItemService.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/ChatRoomResponse.java
  src/main/java/kr/codesquad/secondhand/repository/chat/querydsl/ChatPaginationRepository.java
Labels: feat

#105 4주차 리뷰 반영
  src/main/java/kr/codesquad/secondhand/application/auth/AuthService.java
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/application/redis/RedisService.java
  src/main/java/kr/codesquad/secondhand/application/wishitem/WishItemService.java
  src/main/java/kr/codesquad/secondhand/config/WebConfig.java
  src/main/java/kr/codesquad/secondhand/domain/item/ItemStatus.java
  src/main/java/kr/codesquad/secondhand/exception/UnAuthorizedException.java
  src/main/java/kr/codesquad/secondhand/presentation/ItemController.java
  src/main/java/kr/codesquad/secondhand/presentation/WishItemController.java
  src/main/java/kr/codesquad/secondhand/presentation/interceptor/RegionNotLoginInterceptor.java
  src/main/java/kr/codesquad/secondhand/presentation/support/converter/IsWish.java
  src/test/java/kr/codesquad/secondhand/acceptance/AuthAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/acceptance/ItemAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/item/SalesHistoryServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/wishitem/WishItemServiceTest.java
  src/test/java/kr/codesquad/secondhand/fixture/FixtureFactory.java
Labels: refactor

#107 채팅 목록 조회 테스트
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatRoom.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/ChatRoomResponse.java
  src/main/java/kr/codesquad/secondhand/repository/chat/querydsl/ChatPaginationRepository.java
  src/main/resources/schema.sql
  src/test/java/kr/codesquad/secondhand/SupportRepository.java
  src/test/java/kr/codesquad/secondhand/application/chat/ChatRoomServiceTest.java
  src/test/java/kr/codesquad/secondhand/fixture/FixtureFactory.java
Labels: feat

#108 채팅 전송 기능 구현
  src/main/java/kr/codesquad/secondhand/application/chat/ChatLogService.java
  src/main/java/kr/codesquad/secondhand/application/chat/event/ChatReadEvent.java
  src/main/java/kr/codesquad/secondhand/application/chat/event/ChatReadEventListener.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatLog.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatRoom.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/ChatRequest.java
  src/main/java/kr/codesquad/secondhand/repository/chat/ChatLogRepository.java
  src/test/java/kr/codesquad/secondhand/acceptance/ChatAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/chat/ChatLogServiceTest.java
Labels: feat

#111 채팅방 생성 기능
  src/main/java/kr/codesquad/secondhand/application/chat/ChatRoomService.java
  src/main/java/kr/codesquad/secondhand/application/member/MemberService.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatRoom.java
  src/main/java/kr/codesquad/secondhand/domain/chat/WhoIsLast.java
  src/main/java/kr/codesquad/secondhand/domain/item/Item.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/MemberController.java
  src/main/resources/application-redis.yml
  src/main/resources/schema.sql
  src/test/java/kr/codesquad/secondhand/acceptance/ChatAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/acceptance/MemberAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/chat/ChatLogServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/chat/ChatRoomServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/member/MemberServiceTest.java
  src/test/java/kr/codesquad/secondhand/fixture/FixtureFactory.java
Labels: feat

#113 Spring REST Docs 적용
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/kr/codesquad/secondhand/presentation/dto/member/SignUpRequest.java
  src/main/resources/static/index.html
  src/test/java/kr/codesquad/secondhand/documentation/DocumentationTest.java
  src/test/java/kr/codesquad/secondhand/documentation/DocumentationTestSupport.java
  src/test/java/kr/codesquad/secondhand/documentation/auth/AuthDocumentationTest.java
  src/test/java/kr/codesquad/secondhand/documentation/category/CategoryDocumentationTest.java
  src/test/java/kr/codesquad/secondhand/documentation/support/ConstraintsHelper.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: docs, test

#114 채팅목록에 새로운 채팅 개수 확인 기능 추가
  src/main/java/kr/codesquad/secondhand/application/chat/ChatLogService.java
  src/main/java/kr/codesquad/secondhand/application/chat/ChatRoomService.java
  src/main/java/kr/codesquad/secondhand/application/chat/event/ChatReadEventListener.java
  src/main/java/kr/codesquad/secondhand/application/residence/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatLog.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatRoom.java
  src/main/java/kr/codesquad/secondhand/domain/residence/Residence.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/ChatRoomResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/SimpleChatLog.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/member/AddressData.java
  src/main/java/kr/codesquad/secondhand/repository/chat/ChatLogRepository.java
  src/main/java/kr/codesquad/secondhand/repository/chat/querydsl/ChatCountRepository.java
  src/main/java/kr/codesquad/secondhand/repository/chat/querydsl/ChatPaginationRepository.java
  src/main/resources/schema.sql
  src/test/java/kr/codesquad/secondhand/acceptance/ChatAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/acceptance/ResidenceAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/chat/ChatLogServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/chat/ChatRoomServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/residence/ResidenceServiceTest.java
  src/test/java/kr/codesquad/secondhand/documentation/auth/AuthDocumentationTest.java
  src/test/java/kr/codesquad/secondhand/fixture/FixtureFactory.java
Labels: feat

#117 상품 이미지 관련 로직 수정
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/category.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/item.adoc
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/domain/item/Item.java
  src/main/java/kr/codesquad/secondhand/presentation/ItemController.java
  src/main/resources/static/index.html
  src/test/java/kr/codesquad/secondhand/acceptance/ItemAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemServiceTest.java
  src/test/java/kr/codesquad/secondhand/documentation/auth/AuthDocumentationTest.java
  src/test/java/kr/codesquad/secondhand/documentation/item/ItemDocumentationTest.java
  src/test/resources/item.jpeg
Labels: feat

#120 화면에 보여질 메인 거주지역 선택
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/residence.adoc
  src/main/java/kr/codesquad/secondhand/application/residence/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/presentation/ResidenceController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/residence/ResidenceSelectRequest.java
  src/main/java/kr/codesquad/secondhand/repository/residence/ResidenceRepository.java
  src/main/resources/static/index.html
  src/test/java/kr/codesquad/secondhand/acceptance/ResidenceAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/residence/ResidenceServiceTest.java
  src/test/java/kr/codesquad/secondhand/documentation/residence/ResidenceDocumentationTest.java
Labels: feat

#119 채팅 목록 조회 시 롱폴링 적용
  src/main/java/kr/codesquad/secondhand/application/chat/ChatRoomService.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/CustomSlice.java
  src/main/java/kr/codesquad/secondhand/repository/chat/ChatLogRepository.java
Labels: feat

#122 채팅 목록 조회 시 offset방식으로 변경
  src/main/java/kr/codesquad/secondhand/application/chat/ChatRoomService.java
  src/main/java/kr/codesquad/secondhand/application/image/ImageService.java
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/repository/chat/querydsl/ChatPaginationRepository.java
  src/main/resources/static/index.html
  src/test/java/kr/codesquad/secondhand/application/chat/ChatRoomServiceTest.java
Labels: feat

#125 5주차 리뷰사항 반영
  src/main/java/kr/codesquad/secondhand/application/chat/ChatLogService.java
  src/main/java/kr/codesquad/secondhand/application/chat/ChatRoomService.java
  src/main/java/kr/codesquad/secondhand/application/item/ItemService.java
  src/main/java/kr/codesquad/secondhand/application/item/SalesHistoryService.java
  src/main/java/kr/codesquad/secondhand/application/member/MemberService.java
  src/main/java/kr/codesquad/secondhand/application/residence/ResidenceService.java
  src/main/java/kr/codesquad/secondhand/application/wishitem/WishItemService.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatLog.java
  src/main/java/kr/codesquad/secondhand/domain/chat/ChatRoom.java
  src/main/java/kr/codesquad/secondhand/domain/item/Item.java
  src/main/java/kr/codesquad/secondhand/domain/item/ItemStatus.java
  src/main/java/kr/codesquad/secondhand/domain/itemimage/ItemImage.java
  src/main/java/kr/codesquad/secondhand/domain/residence/Residence.java
  src/main/java/kr/codesquad/secondhand/domain/wishitem/WishItem.java
  src/main/java/kr/codesquad/secondhand/presentation/ChatController.java
  src/main/java/kr/codesquad/secondhand/presentation/MemberController.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/chat/SimpleChatLog.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/item/ItemRegisterRequest.java
  src/main/java/kr/codesquad/secondhand/presentation/dto/member/ModifyProfileResponse.java
  src/main/java/kr/codesquad/secondhand/presentation/support/converter/IsWish.java
  src/main/java/kr/codesquad/secondhand/presentation/support/converter/IsWishRequestConverter.java
  src/main/java/kr/codesquad/secondhand/repository/residence/ResidenceRepository.java
  src/main/java/kr/codesquad/secondhand/repository/residence/querydsl/ResidenceRepositoryImpl.java
  src/test/java/kr/codesquad/secondhand/acceptance/AuthAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/acceptance/ChatAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/acceptance/ItemAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/acceptance/MemberAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/acceptance/ResidenceAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/acceptance/WishItemAcceptanceTest.java
  src/test/java/kr/codesquad/secondhand/application/auth/AuthServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/auth/TokenServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/category/CategoryServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/chat/ChatLogServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/chat/ChatRoomServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/image/ImageServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/item/ItemServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/item/SalesHistoryServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/member/MemberServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/residence/ResidenceServiceTest.java
  src/test/java/kr/codesquad/secondhand/application/wishitem/WishItemServiceTest.java
  src/test/java/kr/codesquad/secondhand/domain/image/ImageFileTest.java
  src/test/java/kr/codesquad/secondhand/infrastructure/jwt/JwtProviderTest.java
Labels: refactor
